#!/usr/bin/env python
# -*- coding:utf-8 -*-

import math

def quadratic_equation(a, b, c):
    s1 = b**2-4*a*c
    if s1>=0:
        x1=(-b+math.sqrt(s1))/(2*a)
        x2=(-b-math.sqrt(s1))/(2*a)
        return x1,x2
    else:
        e = 'No answer'
        return e

i1 = input('请输入二次项:')
i2 = input('请输入一次项:')
i3 = input('请输入常数项:')
i1 = int(i1)
i2 = int(i2)
i3 = int(i3)
q = quadratic_equation(i1, i2, i3)
print(q)
