#!/usr/bin/env python
# -*- coding:utf-8 -*-
l1 = ['电脑','游艇','鼠标垫','手机',]
d1 = dict(enumerate(l1,1))
for i,j in enumerate(l1,1):
    print(i,j)
i1 = input('商品序号：')
i1 = int(i1)
le = len(l1)
if i1>=1 and i1<=le:
    g1 = d1[i1]
    print(g1)
else:
    print('商品不存在')
