#!/usr/bin/env python
# -*- coding:utf-8 -*-
n1 = 0
while True:
    name=raw_input('username>>>')
    pwd=raw_input('password>>>')
    if name == 'lo' and pwd =='123':
        print('pass')
        break
    else:
        print('prohibit')
        n1 = n1+1
        if n1 == 3:
            break
        else:
            pass
print('end')
